from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


# This will create a views generated by order objects from forms.py.
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        # validates data sent in the request
        form = OrderCreateForm(request.POST)
        # if valid ..
        if form.is_valid():
            # .. create a new order in db
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # clear the cart when completed
            cart.clear()

            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})
